embed_dim: 64
mlp_layer: [128, 128, 128]
activation: 'tanh'
dropout: 0.3

val_metrics: [ndcg, recall]
test_metrics: [recall, precision, map, ndcg, mrr, hit]
topk: 100
cutoff: [10, 20, 50, 1, 3, 5]
negative_count: 20
fmeval: False
eval_batch_size: 64
topk_item_step: 200 # used in ranker's topk function to score all items
